import React from 'react';
import { Shield, EyeOff, ServerOff, Cookie, Lock, HardDrive, CheckCircle2 } from 'lucide-react';
import { smartHighlight } from '../../utils/textFormatting';
import { useLanguage } from '../../hooks/useLanguage';

export const PrivacyPolicy: React.FC = () => {
  const { t } = useLanguage();

  return (
    <div style={{ padding: '80px 0', background: 'var(--bg-main)' }}>
      <div className="seo-sections-wrapper" style={{ display: 'flex', flexDirection: 'column', gap: '80px' }}>
        
        {/* Section 1: Hero */}
        <section className="seo-section hero" style={{ padding: '80px 24px' }}>
          <div style={{ maxWidth: 1000, margin: '0 auto', textAlign: 'center' }}>
            <div style={{ display: 'inline-flex', padding: '12px 24px', background: 'var(--brand-gradient)', borderRadius: 100, color: 'white', fontWeight: 800, fontSize: '0.9rem', marginBottom: 40, gap: 12, alignItems: 'center' }}>
              <Shield size={18} /> {t('priv_heroBadge') || 'Transparent Policies'}
            </div>
            <h1 style={{ fontSize: 'clamp(2.5rem, 6vw, 4rem)', fontWeight: 900, marginBottom: 32, color: 'var(--text-main)', letterSpacing: '-0.04em', lineHeight: 1.1, fontFamily: 'Outfit, sans-serif' }}>
              {smartHighlight(t('priv_heroTitle') || 'Your Media Remains Your Business')}
            </h1>
            <p style={{ fontSize: 'clamp(1.2rem, 2.5vw, 1.5rem)', color: 'var(--text-muted)', lineHeight: 1.6, maxWidth: 800, margin: '0 auto' }}>
              {t('priv_heroDesc') || "Unlike traditional online converters that upload your files to unknown servers, our tools run locally in your browser. This fundamentally changes how we handle your data: we don't."}
            </p>
          </div>
        </section>

        {/* Section 2: Zero Data Collection */}
        <section className="seo-section collection" style={{ padding: '80px 24px', background: 'var(--bg-card)' }}>
          <div style={{ maxWidth: 1000, margin: '0 auto', display: 'flex', flexWrap: 'wrap-reverse', gap: 64, alignItems: 'center' }}>
            <div style={{ flex: '1 1 400px' }}>
              <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, marginBottom: 24, color: 'var(--text-main)', lineHeight: 1.2 }}>{t('priv_collectTitle') || "What We Don't Collect"}</h2>
              <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: 32 }}>
                {t('priv_collectDesc') || 'The easiest way to secure user data is to never collect it in the first place. When you use SolveMyMedia, we have absolutely no access to:'}
              </p>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 16 }}>
                {[
                  t('priv_collect1') || "Your original video, audio, or image files.",
                  t('priv_collect2') || "The processed or compressed output files.",
                  t('priv_collect3') || "Your webcam or microphone streams.",
                  t('priv_collect4') || "Any text transcriptions generated by our AI tools."
                ].map((item, i) => (
                  <li key={i} style={{ display: 'flex', alignItems: 'center', gap: 16, fontSize: '1.1rem', color: 'var(--text-main)', fontWeight: 600 }}>
                    <CheckCircle2 size={24} color="var(--brand-primary)" /> {item}
                  </li>
                ))}
              </ul>
            </div>
            <div style={{ flex: '1 1 400px', display: 'flex', justifyContent: 'center' }}>
               <div style={{ padding: 48, background: 'var(--bg-app)', borderRadius: '50%', border: '8px solid var(--bg-main)' }}>
                 <EyeOff size={100} color="var(--brand-secondary)" />
               </div>
            </div>
          </div>
        </section>

        {/* Section 3: How Local Processing Works */}
        <section className="seo-section processing" style={{ padding: '80px 24px' }}>
          <div style={{ maxWidth: 1000, margin: '0 auto' }}>
            <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, textAlign: 'center', marginBottom: 64, color: 'var(--text-main)', lineHeight: 1.2 }}>{t('priv_howTitle') || 'How Local Processing Secures You'}</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 32 }}>
              <div style={{ padding: 40, background: 'var(--bg-card)', borderRadius: 24, border: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
                <ServerOff size={48} color="var(--brand-primary)" style={{ marginBottom: 24 }} />
                <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: 16, color: 'var(--text-main)' }}>{t('priv_how1Title') || 'No Servers Involved'}</h3>
                <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8 }}>{t('priv_how1Desc') || 'All heavy lifting—transcoding, compressing, cutting—is executed directly by your CPU and GPU using WebAssembly.'}</p>
              </div>
              <div style={{ padding: 40, background: 'var(--bg-card)', borderRadius: 24, border: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
                <HardDrive size={48} color="var(--brand-secondary)" style={{ marginBottom: 24 }} />
                <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: 16, color: 'var(--text-main)' }}>{t('priv_how2Title') || 'In-Memory Execution'}</h3>
                <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8 }}>{t('priv_how2Desc') || "Files are temporarily loaded into your browser's isolated memory sandbox and vanish completely when you close the tab."}</p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 4: Analytics and Cookies */}
        <section className="seo-section analytics" style={{ padding: '80px 24px', background: 'var(--bg-card)' }}>
          <div style={{ maxWidth: 1000, margin: '0 auto', display: 'flex', flexWrap: 'wrap', gap: 64, alignItems: 'center' }}>
             <div style={{ flex: '1 1 400px', display: 'flex', justifyContent: 'center' }}>
               <div style={{ width: '100%', maxWidth: 300, padding: 48, background: 'var(--bg-app)', borderRadius: 32, border: '1px solid var(--border-color)', textAlign: 'center' }}>
                  <Cookie size={64} color="var(--text-muted)" style={{ opacity: 0.5, marginBottom: 24 }} />
                  <div style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--text-main)' }}>{t('priv_cookiesBadge') || 'Minimal Cookies'}</div>
               </div>
             </div>
             <div style={{ flex: '1 1 400px' }}>
                <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, marginBottom: 24, color: 'var(--text-main)', lineHeight: 1.2 }}>{t('priv_cookiesTitle') || 'Analytics & Cookies'}</h2>
                <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: 16 }}>
                  {t('priv_cookiesDesc1') || 'We use basic, privacy-respecting analytics (like Plausible or basic local metrics) solely to understand which tools are popular and how to improve our UI. We do not track you across the web.'}
                </p>
                <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8 }}>
                  {t('priv_cookiesDesc2') || 'We use localStorage strictly for saving your UI preferences (like dark mode and default languages) so you don\'t have to set them every time.'}
                </p>
             </div>
          </div>
        </section>

        {/* Section 5: Third-Party Integrations */}
        <section className="seo-section third-party" style={{ padding: '80px 24px' }}>
          <div style={{ maxWidth: 800, margin: '0 auto', textAlign: 'center' }}>
             <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, marginBottom: 24, color: 'var(--text-main)', lineHeight: 1.2 }}>{t('priv_thirdTitle') || 'Third-Party Services'}</h2>
             <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8 }}>
               {t('priv_thirdDesc') || 'Because our app doesn\'t require user accounts, we do not integrate with third-party authentication providers (like Google or Facebook login), and we do not sell any profiles to ad networks. If we ever integrate advertising to cover hosting costs, it will be clearly labeled and non-intrusive.'}
             </p>
          </div>
        </section>
        
        {/* Section 6: Children's Privacy */}
        <section className="seo-section children" style={{ padding: '80px 24px', background: 'var(--brand-gradient)', color: 'white' }}>
          <div style={{ maxWidth: 800, margin: '0 auto', textAlign: 'center' }}>
             <Lock size={48} style={{ marginBottom: 32, opacity: 0.9 }} />
             <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, marginBottom: 24, lineHeight: 1.2 }}>{t('priv_safetyTitle') || 'Commitment to Safety'}</h2>
             <p style={{ fontSize: '1.1rem', opacity: 0.9, lineHeight: 1.8 }}>
               {t('priv_safetyDesc') || 'Our services are designed for general audiences and are completely safe to use. We do not knowingly collect any personal information from children under 13. Since we don\'t collect personal info from anyone, everyone is protected equally.'}
             </p>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="seo-section faq" style={{ padding: '80px 24px' }}>
          <div style={{ maxWidth: 800, margin: '0 auto' }}>
            <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 800, textAlign: 'center', marginBottom: 48, color: 'var(--text-main)', lineHeight: 1.2 }}>{t('priv_faqTitle') || 'Frequently Asked Questions'}</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
              {[
                { q: t('priv_faq1Q') || "Can anyone at SolveMyMedia see my videos?", a: t('priv_faq1A') || "No. It is technically impossible for us to view your videos because they are processed on your computer and never uploaded over the internet." },
                { q: t('priv_faq2Q') || "What happens if I close my browser during processing?", a: t('priv_faq2A') || "The processing is immediately halted, and any temporary data in your browser's memory is instantly wiped by your browser's garbage collector. Nothing is left behind." },
                { q: t('priv_faq3Q') || "Do you sell my data?", a: t('priv_faq3A') || "No. We have no data to sell. We don't require accounts, emails, or personal information to use the tools." }
              ].map((faq, idx) => (
                <div key={idx} style={{ background: 'var(--bg-card)', padding: 32, borderRadius: 20, border: '1px solid var(--border-color)', boxShadow: '0 4px 20px rgba(0,0,0,0.05)' }}>
                  <h3 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: 12, color: 'var(--text-main)', display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                    <span style={{ color: 'var(--brand-primary)' }}>Q:</span> {faq.q}
                  </h3>
                  <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)', lineHeight: 1.8, margin: 0 }}>
                    <strong style={{ color: 'var(--brand-secondary)' }}>A:</strong> {faq.a}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

      </div>
    </div>
  );
};
