const fs = require('fs');
const path = require('path');
const translate = require('google-translate-api-x');
const { transliterate } = require('transliteration');
const slugify = require('slugify');

const TARGET_FILE = path.join(__dirname, '..', 'src', 'i18n', 'slugs.ts');
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

const langs = ['id','es','fr','de','ja','zh','pt','ru','ar','hi','it','ko','nl','tr','pl','vi','th','sv','cs','da','el','fi','he','hu','no','ro','sk','uk','ms'];

const standardSlugs = [
  'compress-video', 'compress-audio', 'convert-video', 'convert-audio', 
  'video-to-audio', 'transcribe', 'recorder', 'create-gif', 'video-speed', 
  'crop-video', 'mute-video', 'watermark-video', 'merge-audio'
];

// Clean text for translation
const slugToText = (slug) => slug.split('-').join(' ');

async function main() {
  console.log('Generating localized slugs...');
  const slugsObj = {};
  
  // English is the base
  slugsObj['en'] = {};
  standardSlugs.forEach(s => slugsObj['en'][s] = s);
  
  for (let lang of langs) {
    console.log(`[${lang}] Translating slugs...`);
    const targetLang = lang === 'zh' ? 'zh-CN' : (lang === 'he' ? 'iw' : lang);
    slugsObj[lang] = {};
    
    try {
      const textsToTranslate = standardSlugs.map(slugToText);
      const res = await translate(textsToTranslate, { to: targetLang, forceBatch: false, rejectOnPartialFail: false });
      const translatedTexts = Array.isArray(res) ? res.map(r => r.text) : [res.text];
      
      translatedTexts.forEach((text, i) => {
        // Transliterate to ASCII
        let trans = transliterate(text);
        // Slugify (lowercase, remove symbols, spaces to hyphens)
        let localizedSlug = slugify(trans, { lower: true, strict: true });
        
        // Fallback to standard slug if transliteration results in empty string
        if (!localizedSlug) localizedSlug = standardSlugs[i];
        
        slugsObj[lang][standardSlugs[i]] = localizedSlug;
      });
      
      console.log(`[${lang}] Done.`);
      await sleep(500); // Rate limiting
    } catch (err) {
      console.error(`[${lang}] Error:`, err.message);
      // Fallback to English slugs on error
      standardSlugs.forEach(s => slugsObj[lang][s] = s);
    }
  }

  // Generate TS file content
  let tsContent = `// Automatically generated by scripts/generate-slugs.cjs\n\n`;
  tsContent += `export const SLUGS_MAP: Record<string, Record<string, string>> = ${JSON.stringify(slugsObj, null, 2)};\n\n`;
  
  tsContent += `
export const getLocalizedSlug = (standardSlug: string, lang: string): string => {
  if (SLUGS_MAP[lang] && SLUGS_MAP[lang][standardSlug]) {
    return SLUGS_MAP[lang][standardSlug];
  }
  return standardSlug;
};

export const getStandardSlug = (localizedSlug: string, lang: string): string => {
  if (!SLUGS_MAP[lang]) return localizedSlug;
  const standardSlug = Object.keys(SLUGS_MAP[lang]).find(key => SLUGS_MAP[lang][key] === localizedSlug);
  return standardSlug || localizedSlug;
};
`;

  fs.writeFileSync(TARGET_FILE, tsContent);
  console.log('Successfully wrote src/i18n/slugs.ts');
}

main();
