const fs = require('fs');
const path = require('path');
const { translate } = require('google-translate-api-x');

const translationsPath = path.join(__dirname, '../src/i18n/translations.ts');

const LEGAL_STRINGS = {
  // About Us
  about_heroBadge: "Our Story",
  about_heroTitle: "Building the Future of Local Software",
  about_heroDesc: "We believe powerful media tools shouldn't cost a subscription fee or compromise your privacy. That's why we're bringing desktop-class processing directly to your browser.",
  about_missionTitle: "Our Mission",
  about_missionDesc: "The internet is saturated with shady online converters that harvest your files, bombard you with ads, and demand monthly fees. Our mission is to democratize media creation by providing free, private, and open-source-powered tools that run 100% locally on your machine.",
  about_statNum: "0",
  about_statDesc: "Files uploaded to our servers. Ever.",
  about_valuesTitle: "Our Core Values",
  about_val1Title: "Absolute Privacy",
  about_val1Desc: "Your files never leave your device.",
  about_val2Title: "Unmatched Speed",
  about_val2Desc: "We utilize your hardware, not sluggish cloud servers.",
  about_val3Title: "Free for Everyone",
  about_val3Desc: "No hidden fees, no watermarks, no subscriptions.",
  about_techTitle: "Powered by Modern Web Standards",
  about_techDesc: "We harness the bleeding edge of web technology—WebAssembly, WebCodecs, and WebGPU—to port complex C++ algorithms directly into JavaScript.",
  about_probTitle: "Why We Built This",
  about_probDesc: "Have you ever tried to compress a 2GB video online? You have to wait 20 minutes to upload it, pay a fee to bypass the 500MB limit, wait for it to process, and then wait to download it. It's broken. By running everything locally, we bypass the cloud entirely.",
  about_probPoint1: "Cloud limits and long wait times",
  about_probPoint2: "Paying $15/mo for basic compression",
  about_secTitle: "Security by Design",
  about_secDesc: "Because our app runs completely client-side, we don't need complex data processing agreements or privacy policies to explain what we do with your data. We simply don't have your data. You can disconnect from the internet and continue using the app.",
  about_faqTitle: "Frequently Asked Questions",
  about_faq1Q: "How does the company make money?",
  about_faq1A: "Currently, SolveMyMedia is completely free and funded out of pocket. We believe in building great tools first. In the future, we may introduce opt-in premium features for power users, but the core tools will remain free.",
  about_faq2Q: "Can I contribute to the project?",
  about_faq2A: "Yes! We are huge advocates for the open-source community. You can reach out to our team to find ways to contribute or report issues.",
  about_faq3Q: "Where is the team based?",
  about_faq3A: "We are a distributed team of engineers passionate about pushing the limits of what a web browser can do, operating globally across multiple time zones.",

  // Privacy Policy
  priv_heroBadge: "Transparent Policies",
  priv_heroTitle: "Your Media Remains Your Business",
  priv_heroDesc: "Unlike traditional online converters that upload your files to unknown servers, our tools run locally in your browser. This fundamentally changes how we handle your data: we don't.",
  priv_collectTitle: "What We Don't Collect",
  priv_collectDesc: "The easiest way to secure user data is to never collect it in the first place. When you use SolveMyMedia, we have absolutely no access to:",
  priv_collect1: "Your original video, audio, or image files.",
  priv_collect2: "The processed or compressed output files.",
  priv_collect3: "Your webcam or microphone streams.",
  priv_collect4: "Any text transcriptions generated by our AI tools.",
  priv_howTitle: "How Local Processing Secures You",
  priv_how1Title: "No Servers Involved",
  priv_how1Desc: "All heavy lifting—transcoding, compressing, cutting—is executed directly by your CPU and GPU using WebAssembly.",
  priv_how2Title: "In-Memory Execution",
  priv_how2Desc: "Files are temporarily loaded into your browser's isolated memory sandbox and vanish completely when you close the tab.",
  priv_cookiesBadge: "Minimal Cookies",
  priv_cookiesTitle: "Analytics & Cookies",
  priv_cookiesDesc1: "We use basic, privacy-respecting analytics (like Plausible or basic local metrics) solely to understand which tools are popular and how to improve our UI. We do not track you across the web.",
  priv_cookiesDesc2: "We use localStorage strictly for saving your UI preferences (like dark mode and default languages) so you don't have to set them every time.",
  priv_thirdTitle: "Third-Party Services",
  priv_thirdDesc: "Because our app doesn't require user accounts, we do not integrate with third-party authentication providers (like Google or Facebook login), and we do not sell any profiles to ad networks. If we ever integrate advertising to cover hosting costs, it will be clearly labeled and non-intrusive.",
  priv_safetyTitle: "Commitment to Safety",
  priv_safetyDesc: "Our services are designed for general audiences and are completely safe to use. We do not knowingly collect any personal information from children under 13. Since we don't collect personal info from anyone, everyone is protected equally.",
  priv_faqTitle: "Frequently Asked Questions",
  priv_faq1Q: "Can anyone at SolveMyMedia see my videos?",
  priv_faq1A: "No. It is technically impossible for us to view your videos because they are processed on your computer and never uploaded over the internet.",
  priv_faq2Q: "What happens if I close my browser during processing?",
  priv_faq2A: "The processing is immediately halted, and any temporary data in your browser's memory is instantly wiped by your browser's garbage collector. Nothing is left behind.",
  priv_faq3Q: "Do you sell my data?",
  priv_faq3A: "No. We have no data to sell. We don't require accounts, emails, or personal information to use the tools.",

  // Terms of Service
  terms_heroBadge: "Legal Agreement",
  terms_heroTitle: "Terms of Service",
  terms_heroDesc: "By accessing and using SolveMyMedia's tools, you agree to be bound by the following terms. We've kept them as simple and readable as possible.",
  terms_useTitle: "Acceptable Use",
  terms_useDesc: "Our tools are provided for personal and commercial use. However, you must not use our services to process illegal content, infringe on intellectual property rights, or distribute malware. Since the processing is done locally, you bear full legal responsibility for the files you generate.",
  terms_rule1: "No Illegal Content",
  terms_rule2: "No Copyright Infringement",
  terms_rule3: "No Reverse Engineering of UI",
  terms_ipTitle: "Intellectual Property",
  terms_ipDesc: "The website design, branding, logo, and original UI code belong to SolveMyMedia. The underlying media processing technologies (like FFmpeg.wasm, ONNX, and others) belong to their respective open-source creators and are used under their permissive licenses (MIT, Apache, etc.). You retain all rights to the media you process.",
  terms_asIs: "\"AS-IS\" BASIS",
  terms_warrantyTitle: "No Warranty",
  terms_warrantyDesc1: "Our services are provided on an \"as is\" and \"as available\" basis without any warranties of any kind. We do not guarantee that the service will be uninterrupted or error-free.",
  terms_warrantyDesc2: "Experimental browser features (like WebCodecs) can crash tabs on older devices. Always keep a backup of your original files before processing them.",
  terms_liabilityTitle: "Limitation of Liability",
  terms_liabilityDesc: "In no event shall SolveMyMedia, its developers, or its affiliates be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.",
  terms_modTitle: "Modifications",
  terms_modDesc: "We reserve the right to modify or replace these Terms at any time. We will try to provide at least 30 days notice prior to any new terms taking effect.",
  terms_contactTitle: "Contact Us",
  terms_contactDesc: "If you have any questions about these Terms, please contact us at legal@solvemymedia.com.",
  terms_faqTitle: "Frequently Asked Questions",
  terms_faq1Q: "Can I use the output videos for commercial purposes?",
  terms_faq1A: "Yes. Since the processing is done locally on your machine, you retain all copyrights and commercial rights to the files you create and process using our tools.",
  terms_faq2Q: "Do you claim ownership of my uploaded media?",
  terms_faq2A: "No. You retain all rights. Furthermore, because we do not have servers to receive your files, we literally cannot store, copy, or claim ownership of your media.",
  terms_faq3Q: "Can I use your website in an iframe on my own site?",
  terms_faq3A: "No, embedding our tools inside iframes or redistributing our application as a white-label service without explicit written permission is prohibited.",

  // Security & Trust
  sec_heroBadge: "Enterprise-Grade Security",
  sec_heroTitle: "Trust Through Architecture",
  sec_heroDesc: "We didn't just write a privacy policy. We engineered a system where a data breach is mathematically and physically impossible.",
  sec_zeroTrustTitle: "Zero-Trust by Default",
  sec_zeroTrustDesc: "In a standard web app, you must trust the server not to steal your data. In our Zero-Trust architecture, you don't even have to trust us. The web browser acts as an impenetrable sandbox. The files you select never leave your local environment.",
  sec_wasmTitle: "WebAssembly Isolation",
  sec_wasm1Title: "Memory Sandboxing",
  sec_wasm1Desc: "The FFmpeg and AI binaries run in a strict WebAssembly sandbox. They cannot access your file system or network without explicit permission.",
  sec_wasm2Title: "Network Isolation",
  sec_wasm2Desc: "Once the initial scripts are downloaded, the application can operate entirely offline. Try it yourself by turning off your Wi-Fi.",
  sec_tlsTitle: "Secure Delivery (TLS 1.3)",
  sec_tlsDesc: "The initial connection to download our web application is secured using enterprise-grade TLS 1.3 encryption. This guarantees that the code running in your browser has not been tampered with by man-in-the-middle attacks.",
  sec_complianceTitle: "GDPR & CCPA Compliant",
  sec_complianceDesc: "Because we process all user files locally, we are inherently compliant with the strictest data protection laws globally, including GDPR and CCPA.",
  sec_compBadge1: "EU GDPR",
  sec_compBadge2: "US CCPA",
  sec_compBadge3: "HIPAA Ready",
  sec_alwaysComp: "Always Compliant",
  sec_openTitle: "Built on Open Source",
  sec_openDesc: "The core processing engines that power SolveMyMedia (like FFmpeg and ONNX Runtime) are open-source and regularly audited by thousands of developers and security researchers worldwide. This provides a level of security transparency that proprietary closed-source cloud services simply cannot match.",
  sec_faqTitle: "Frequently Asked Questions",
  sec_faq1Q: "Is it safe to compress confidential legal or medical videos here?",
  sec_faq1A: "Yes. Because the videos never leave your device, this tool is safe to use even in strict, highly regulated corporate environments like hospitals or law firms.",
  sec_faq2Q: "How do I know my files aren't being uploaded secretly?",
  sec_faq2A: "You can verify this yourself! Open your browser's Developer Tools (F12), navigate to the Network tab, and watch the traffic while you compress a video. You will see zero outbound traffic.",
  sec_faq3Q: "Are your SSL certificates up to date?",
  sec_faq3A: "Yes, our domain is secured with modern SSL/TLS certificates enforcing HTTPS for all connections.",

  // Pricing
  price_heroBadge: "Transparent Pricing",
  price_heroTitle: "Everything is 100% Free",
  price_heroDesc: "No monthly subscriptions. No credit cards required. No watermarks on your exports. Because you are using your own hardware to process the files, we have zero server costs—and we pass those savings entirely to you.",
  price_tableTitle: "Why Pay for Cloud?",
  price_compTitle: "Typical Cloud Converter",
  price_compPrice: "$15",
  price_compPeriod: "/mo",
  price_comp1: "Upload limits (usually 500MB)",
  price_comp2: "Wait in processing queues",
  price_comp3: "Risk data breaches",
  price_comp4: "Slow download speeds",
  price_ourBadge: "YOUR BEST OPTION",
  price_ourTitle: "SolveMyMedia",
  price_ourPrice: "$0",
  price_ourPeriod: "/forever",
  price_our1: "No upload limits (up to 2GB tested)",
  price_our2: "Instant processing start",
  price_our3: "Zero-Trust Local Privacy",
  price_our4: "Instant downloads",
  price_noSubsTitle: "Ditch the Subscriptions",
  price_noSubsDesc: "Subscription fatigue is real. Why should you pay a monthly fee to compress a single video or convert an audio file twice a year? We believe utility software should be free and accessible whenever you need it, without forcing you to remember to cancel a trial.",
  price_noPremium: "No Premium Tiers",
  price_limitsTitle: "Unlimited File Sizes",
  price_limitsDesc: "Unlike cloud services that restrict you to 100MB or 500MB unless you pay, our limits are strictly dictated by your browser's memory. If your device has enough RAM, you can process massive 2GB+ files completely for free.",
  price_openCore: "Open Source Core",
  price_whyFreeTitle: "How Can We Afford This?",
  price_whyFreeDesc: "Hosting large file processing servers costs thousands of dollars a month. Hosting a static web application that offloads all the processing to your local computer costs mere pennies. By utilizing your device's power, we completely eliminate our largest overhead, allowing us to keep this service free forever.",
  price_inclTitle: "Everything Included",
  price_feat1: "No Watermarks on any exports",
  price_feat2: "Unlimited processing queues",
  price_feat3: "Full privacy & data security",
  price_feat4: "Advanced AI tools (Whisper)",
  price_feat5: "Full WebCodecs acceleration",
  price_faqTitle: "Frequently Asked Questions",
  price_faq1Q: "Is there really no hidden catch?",
  price_faq1A: "No catch. Our app executes the logic on your machine. You supply the processing power, so we don't have to pay for expensive cloud servers.",
  price_faq2Q: "Will you ever charge for this?",
  price_faq2A: "The core tools you see today will always remain free. We may introduce optional, completely separate premium features later, but we will never restrict what's already free.",
  price_faq3Q: "Do I need to create an account?",
  price_faq3A: "No! Since we don't charge you or save your files, there is absolutely no need for an account system.",

  // Compare
  cmp_heroBadge: "A Better Way",
  cmp_heroTitle: "Cloud vs Local Processing",
  cmp_heroDesc: "For 15 years, online tools have relied on a broken paradigm: uploading huge files to distant servers just to make a small edit. We are changing that forever.",
  cmp_speedTitle: "Speed is Everything",
  cmp_speedDesc: "With a cloud tool, you have to wait to upload your 1GB file, wait for it to process, and then wait to download the result. With SolveMyMedia, processing starts the millisecond you drop the file.",
  cmp_cloudLabel: "Cloud",
  cmp_cloudTime: "25 mins",
  cmp_localLabel: "Local",
  cmp_localTime: "2 mins",
  cmp_privacyTitle: "Who Controls Your Data?",
  cmp_cloudCardTitle: "Cloud Converters",
  cmp_cloudPoint1: "Uploads your files to unknown servers",
  cmp_cloudPoint2: "Files can be intercepted during transfer",
  cmp_cloudPoint3: "Risk of files remaining on their servers",
  cmp_ourCardTitle: "SolveMyMedia",
  cmp_ourPoint1: "Files never leave your local device",
  cmp_ourPoint2: "Mathematically immune to MITM data theft",
  cmp_ourPoint3: "Works entirely offline after loading",
  cmp_limitsTitle: "No Arbitrary File Limits",
  cmp_limitsDesc: "Traditional converters impose strict limits (like 100MB) because server bandwidth is incredibly expensive. Since we don't use server bandwidth, we don't have to restrict you. If your browser has enough memory, you can compress a 3GB 4K video easily.",
  cmp_costTitle: "The True Cost of Cloud",
  cmp_costDesc: "Cloud converters usually hook you with a free tier, then block your IP if you use it too much or demand a $15/month subscription. We have no hidden fees. We built this tool to break the cycle of expensive SaaS utilities.",
  cmp_qualTitle: "Same Engines, Better Experience",
  cmp_qualDesc: "Don't mistake \"local\" for \"low quality.\" Our web application uses the exact same industry-standard engines (FFmpeg and OpenAI Whisper) that the premium cloud services use on their backends. The only difference is we run them on your machine via WebAssembly.",
  cmp_faqTitle: "Frequently Asked Questions",
  cmp_faq1Q: "If it's running locally, won't it drain my battery?",
  cmp_faq1A: "Processing heavy videos will utilize your CPU, which does consume battery, similar to playing a 3D game. However, it's often much faster than waiting for an upload/download cycle on a weak connection.",
  cmp_faq2Q: "Is the output quality the same as paid cloud tools?",
  cmp_faq2A: "Yes. We use the exact same FFmpeg libraries under the hood that major platforms use. The quality is identical.",
  cmp_faq3Q: "Do I need a powerful computer to use this?",
  cmp_faq3A: "While a faster computer will compress files much quicker, even older laptops can run our WebAssembly tools perfectly fine—it just might take a little longer.",

  // Supported Languages
  lang_heroBadge: "Global Reach",
  lang_heroTitle: "Built for a Global Audience",
  lang_heroDesc: "Whether you are transcribing a Spanish interview or navigating the app in Indonesian, SolveMyMedia is designed to break down language barriers locally.",
  lang_uiTitle: "App Interface Localization",
  lang_uiDesc: "We are actively working to translate our entire user interface so you can compress and edit your videos in your native language. Currently, the app interface fully supports 32 languages including:",
  lang_whisperTitle: "AI Transcription Capabilities",
  lang_whisperDesc: "Our Transcribe tool uses optimized Whisper models via WebAssembly. It can automatically detect and transcribe over 90 languages with near-human accuracy directly in your browser.",
  lang_stat1Num: "90+",
  lang_stat1Label: "Languages Detected Automatically",
  lang_stat2Num: "100%",
  lang_stat2Label: "Offline Processing (No APIs)",
  lang_stat3Num: "4",
  lang_stat3Label: "Export Formats (SRT, VTT, TXT, JSON)",
  lang_accuracyTitle: "A Note on Accuracy",
  lang_accuracyDesc1: "Because the AI models are running directly on your CPU/GPU inside a web browser, we use heavily quantized (compressed) versions of the Whisper model to prevent your computer from freezing.",
  lang_accuracyDesc2: "While accuracy is incredibly high for major languages like English, Spanish, and French, some niche dialects may experience lower transcription accuracy compared to massive cloud models.",
  lang_suggestTitle: "Help Us Translate",
  lang_suggestDesc: "SolveMyMedia is built by the community, for the community. If you don't see your native language in our UI localization list and want to help translate the interface, we would love your help!",
  lang_githubBtn: "Contribute on GitHub",
  lang_mapTitle: "Global Delivery",
  lang_mapDesc: "No matter where you are in the world, the application files are delivered via an ultra-fast global CDN. Once downloaded (usually under 2 seconds), you have a full desktop-class media suite running entirely offline in your location.",
  lang_faqTitle: "Frequently Asked Questions",
  lang_faq1Q: "Can I translate from one language to another?",
  lang_faq1A: "Currently, the AI transcribe tool focuses on transcribing spoken audio into text in its native language. Translation features (e.g., spoken Spanish to English text) are on our roadmap.",
  lang_faq2Q: "Why is the AI getting some words wrong in my language?",
  lang_faq2A: "To run inside a browser, we use a smaller 30MB AI model instead of a 3GB cloud model. It's incredibly fast and private, but it sacrifices a tiny bit of vocabulary depth for niche languages.",
  lang_faq3Q: "How do I change the UI language?",
  lang_faq3A: "You can change the language using the language dropdown located in the Navbar. Your preference will be saved locally for your next visit."
};

const LANG_MAP = {
  'zh': 'zh-CN',
  'zh-TW': 'zh-TW',
  'he': 'iw'
};

const ALL_LANGS = [
  'id', 'es', 'fr', 'de', 'ja', 'pt', 'ru', 'zh', 'zh-TW', 'ar', 'hi',
  'it', 'ko', 'nl', 'tr', 'pl', 'vi', 'th', 'sv', 'cs', 'da', 'el',
  'fi', 'he', 'hu', 'no', 'ro', 'sk', 'uk', 'ms', 'tl'
];

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

async function main() {
  console.log('Reading translations.ts...');
  let content = fs.readFileSync(translationsPath, 'utf8');
  const hadCrlf = content.includes('\r\n');
  content = content.replace(/\r\n/g, '\n');

  // 1. Add to UiDictionary interface
  const keys = Object.keys(LEGAL_STRINGS);
  let uiDictAdditions = '';
  keys.forEach(k => {
    if (!content.includes(`  ${k}?: string;`)) {
      uiDictAdditions += `  ${k}?: string;\n`;
    }
  });

  if (uiDictAdditions) {
    const target = 'export interface UiDictionary {\n  [key: string]: string | undefined;\n';
    content = content.replace(target, target + uiDictAdditions);
    console.log(`Added ${keys.length} type definitions to UiDictionary.`);
  }

  // 2. Add to baseDict (English)
  let baseDictAdditions = '';
  keys.forEach(k => {
    if (!content.includes(`  ${k}: `)) {
      baseDictAdditions += `  ${k}: ${JSON.stringify(LEGAL_STRINGS[k])},\n`;
    }
  });

  if (baseDictAdditions) {
    const target = 'const baseDict: UiDictionary = {\n';
    content = content.replace(target, target + baseDictAdditions);
    console.log(`Added ${keys.length} base definitions to baseDict.`);
  }

  fs.writeFileSync(translationsPath, hadCrlf ? content.replace(/\n/g, '\r\n') : content, 'utf8');

  // 3. Batch translate and inject for all other 31 languages
  const keyList = Object.keys(LEGAL_STRINGS);
  const valList = Object.values(LEGAL_STRINGS);

  // Chunk keys/values into batches of 30 to prevent any payload size limit in google translate
  const CHUNK_SIZE = 30;
  const chunks = [];
  for (let i = 0; i < keyList.length; i += CHUNK_SIZE) {
    chunks.push({
      keys: keyList.slice(i, i + CHUNK_SIZE),
      vals: valList.slice(i, i + CHUNK_SIZE)
    });
  }

  console.log(`Total strings to translate per language: ${keyList.length} (${chunks.length} chunks)`);

  for (let i = 0; i < ALL_LANGS.length; i++) {
    const lang = ALL_LANGS[i];
    const targetCode = LANG_MAP[lang] || lang;
    console.log(`[${i + 1}/${ALL_LANGS.length}] Translating legal pages for ${lang} (${targetCode})...`);

    content = fs.readFileSync(translationsPath, 'utf8').replace(/\r\n/g, '\n');
    const langRegex = new RegExp(`(\\n\\s{2}['"]?${lang}['"]?:\\s*\\{[\\s\\S]*?\\n\\s{2}\\},)`);
    const match = content.match(langRegex);

    if (!match) {
      console.error(`Could not find language block for ${lang}!`);
      continue;
    }

    let langBlock = match[1];
    if (langBlock.includes('about_heroBadge:')) {
      console.log(`  -> Already translated for ${lang}`);
      continue;
    }

    const translatedObj = {};

    for (const chunk of chunks) {
      let attempts = 0;
      let success = false;
      let chunkResults = [];

      while (attempts < 3 && !success) {
        try {
          const res = await translate(chunk.vals, { to: targetCode });
          chunkResults = Array.isArray(res) ? res.map(r => r.text) : [res.text];
          if (chunkResults.length === chunk.vals.length) {
            success = true;
          } else {
            throw new Error(`Length mismatch: expected ${chunk.vals.length}, got ${chunkResults.length}`);
          }
        } catch (err) {
          attempts++;
          console.warn(`  Retry ${attempts} for ${lang} chunk: ${err.message}`);
          await sleep(600 * attempts);
        }
      }

      if (!success) {
        console.error(`  Fallback to individual item translation for ${lang}`);
        chunkResults = [];
        for (const text of chunk.vals) {
          try {
            const res = await translate(text, { to: targetCode });
            chunkResults.push(res.text);
            await sleep(50);
          } catch (e) {
            chunkResults.push(text);
          }
        }
      }

      chunk.keys.forEach((key, idx) => {
        translatedObj[key] = chunkResults[idx] || LEGAL_STRINGS[key];
      });

      await sleep(150);
    }

    const injectionLines = Object.entries(translatedObj)
      .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
      .join('\n');

    const lastBraceIdx = langBlock.lastIndexOf('\n  },');
    if (lastBraceIdx !== -1) {
      const newBlock = langBlock.slice(0, lastBraceIdx) + '\n' + injectionLines + langBlock.slice(lastBraceIdx);
      content = content.replace(langBlock, newBlock);
      fs.writeFileSync(translationsPath, hadCrlf ? content.replace(/\n/g, '\r\n') : content, 'utf8');
      console.log(`  -> Successfully injected ${keyList.length} strings for ${lang}`);
    } else {
      console.error(`  -> Failed to find closing brace for ${lang}`);
    }

    await sleep(200);
  }

  console.log('ALL 32 LANGUAGES LEGAL & RESOURCES TRANSLATION COMPLETED!');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
